# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stack < Formula
  desc "Stacked branch workflow tool for managing atomic commits"
  homepage "https://github.com/wsoule/stack"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wsoule/stack/releases/download/v0.1.2/stack_darwin_amd64.tar.gz"
      sha256 "facc28c5e36cfc1a95ecc02f84f21e854bb4858a983d0d26c829766a24a9fe78"

      def install
        bin.install "ac"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wsoule/stack/releases/download/v0.1.2/stack_darwin_arm64.tar.gz"
      sha256 "10442e5541b01e43c1664980848dd3b7d675783afbe009baad39d51e4fad853b"

      def install
        bin.install "ac"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wsoule/stack/releases/download/v0.1.2/stack_linux_amd64.tar.gz"
      sha256 "f7a952163e5d80f7121fcddbca29e1e4c5be0ba085728b688e7c48cc5b8020ec"
      def install
        bin.install "ac"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wsoule/stack/releases/download/v0.1.2/stack_linux_arm64.tar.gz"
      sha256 "149d4081a21f1ffbaf354f8eb57ca32443fae9fc717950752f01a10dc7a4478c"
      def install
        bin.install "ac"
      end
    end
  end

  test do
    system "#{bin}/ac", "--help"
  end
end
