# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class St < Formula
  desc "Stacked branch workflow tool for managing atomic commits"
  homepage "https://github.com/wsoule/stack"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wsoule/stack/releases/download/v0.1.7/st_darwin_amd64.tar.gz"
      sha256 "22fa08468ffd810b610990d4fdfcf8720b3d1f0816ca92af26c41b95b4fb5903"

      def install
        bin.install "st"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wsoule/stack/releases/download/v0.1.7/st_darwin_arm64.tar.gz"
      sha256 "f1ad71000e4e353d3c3c3a59ca9461ca2d849a96401555b5904e154d2aced60c"

      def install
        bin.install "st"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wsoule/stack/releases/download/v0.1.7/st_linux_amd64.tar.gz"
      sha256 "b43fa0f4823050ceea039d00b5b9bf5066a4c0d8cb4af8aeaa709e214323e7ed"
      def install
        bin.install "st"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wsoule/stack/releases/download/v0.1.7/st_linux_arm64.tar.gz"
      sha256 "da32b1028ffb6d7cd8c68ab3308ea28e60bd1138cd2c3e889d074e167131b4f0"
      def install
        bin.install "st"
      end
    end
  end

  test do
    system "#{bin}/st", "--help"
  end
end
