# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stack < Formula
  desc "Stacked branch workflow tool for managing atomic commits"
  homepage "https://github.com/wsoule/stack"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wsoule/stack/releases/download/v0.1.5/stack_darwin_amd64.tar.gz"
      sha256 "f1678f432c7c416ade15d6c1382fdfc27c24680c6332a06d51eba3f14ca2461c"

      def install
        bin.install "st"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wsoule/stack/releases/download/v0.1.5/stack_darwin_arm64.tar.gz"
      sha256 "3f6af51a4d582d28962684b62d51462f960bfe16ded83f612e5516701f563572"

      def install
        bin.install "st"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wsoule/stack/releases/download/v0.1.5/stack_linux_amd64.tar.gz"
      sha256 "2e36d77aa5d5e97cfb6fddb846f7500bf5b96c26dc3fd53b66cc910f208b78eb"
      def install
        bin.install "st"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wsoule/stack/releases/download/v0.1.5/stack_linux_arm64.tar.gz"
      sha256 "15576ea1acf011ec9fdd85fb5048a7b6b533c4c224598e2b2e7da9c9a2d0ad3e"
      def install
        bin.install "st"
      end
    end
  end

  test do
    system "#{bin}/st", "--help"
  end
end
