# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stack < Formula
  desc "Stacked branch workflow tool for managing atomic commits"
  homepage "https://github.com/wsoule/stack"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wsoule/stack/releases/download/v0.1.3/stack_darwin_amd64.tar.gz"
      sha256 "3eb692e1577c51fdcae7137128bd184ca9ab63fab18afbf91ba638260b5f5522"

      def install
        bin.install "ac"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wsoule/stack/releases/download/v0.1.3/stack_darwin_arm64.tar.gz"
      sha256 "154dc5ca31e676a9a525124976d44fc834f1dc5953b12c07f0a0da31b34d15c8"

      def install
        bin.install "ac"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wsoule/stack/releases/download/v0.1.3/stack_linux_amd64.tar.gz"
      sha256 "842d44b3af471c3d54f0685c801bafe14bdca9a94b061a546eaef9dce7f196c3"
      def install
        bin.install "ac"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wsoule/stack/releases/download/v0.1.3/stack_linux_arm64.tar.gz"
      sha256 "fe8d6ee70694bf743eb53e3da71015c9ca7cf211bcbce47d2538e48b049ad063"
      def install
        bin.install "ac"
      end
    end
  end

  test do
    system "#{bin}/ac", "--help"
  end
end
